version: "3.7"
services:
  app:
    build:
      args:
        user: kamil
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: typer
    container_name: typer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - typer

  redis:
    image: redis:latest
    container_name: typer-redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data  
    networks:
      - typer 

  db:
    image: mysql:8.0
    container_name: typer-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_HOST: ${DB_HOST}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - typer

  nginx:
    image: nginx:alpine
    container_name: typer-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - typer

volumes:
  redis-data: 

networks:
  typer:
    driver: bridge
